
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package power.forestxreborn.init;

import power.forestxreborn.item.WineItem;
import power.forestxreborn.item.WhiteMulberryItem;
import power.forestxreborn.item.SilverSwordItem;
import power.forestxreborn.item.SilverShovelItem;
import power.forestxreborn.item.SilverPickaxeItem;
import power.forestxreborn.item.SilverNuggetItem;
import power.forestxreborn.item.SilverIngotItem;
import power.forestxreborn.item.SilverHoeItem;
import power.forestxreborn.item.SilverAxeItem;
import power.forestxreborn.item.SilverArmorItem;
import power.forestxreborn.item.SarbakanItem;
import power.forestxreborn.item.SapphireItem;
import power.forestxreborn.item.RawSilverItem;
import power.forestxreborn.item.RawGingerbreadPineItem;
import power.forestxreborn.item.RawGingerbreadManItem;
import power.forestxreborn.item.RawGingerbreadHeartItem;
import power.forestxreborn.item.RawGingerbreadCockItem;
import power.forestxreborn.item.RawGingerbreadBrickItem;
import power.forestxreborn.item.RawBarbecueItem;
import power.forestxreborn.item.RaspberryItem;
import power.forestxreborn.item.QuiverItem;
import power.forestxreborn.item.PolarBearPeltItem;
import power.forestxreborn.item.PolarBearArmorItem;
import power.forestxreborn.item.PeatPieceItem;
import power.forestxreborn.item.MusicDiscStrofaItem;
import power.forestxreborn.item.MeatLoafItem;
import power.forestxreborn.item.LettuceSeedItem;
import power.forestxreborn.item.LettuceItem;
import power.forestxreborn.item.LardItem;
import power.forestxreborn.item.GrapeItem;
import power.forestxreborn.item.GlazedGingerbreadPineItem;
import power.forestxreborn.item.GlazedGingerbreadMenItem;
import power.forestxreborn.item.GingerbreadRoundItem;
import power.forestxreborn.item.GingerbreadPineItem;
import power.forestxreborn.item.GingerbreadManItem;
import power.forestxreborn.item.GingerbreadHeartItem;
import power.forestxreborn.item.GingerbreadFormPineItem;
import power.forestxreborn.item.GingerbreadFormManItem;
import power.forestxreborn.item.GingerbreadFormHeartItem;
import power.forestxreborn.item.GingerbreadFormCockItem;
import power.forestxreborn.item.GingerbreadFormBrickItem;
import power.forestxreborn.item.GingerbreadDoughItem;
import power.forestxreborn.item.GingerbreadCockItem;
import power.forestxreborn.item.GingerbreadBrickItem;
import power.forestxreborn.item.DartItem;
import power.forestxreborn.item.CalibriFeatherItem;
import power.forestxreborn.item.BrownBearPeltItem;
import power.forestxreborn.item.BrownBearArmorItem;
import power.forestxreborn.item.BreadwithlardItem;
import power.forestxreborn.item.BlueberryItem;
import power.forestxreborn.item.BlackMulberryItem;
import power.forestxreborn.item.BerryStrudelItem;
import power.forestxreborn.item.BarbecueItem;
import power.forestxreborn.ForestMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

public class ForestModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ForestMod.MODID);
	public static final RegistryObject<Item> SNAIL_SHELL = block(ForestModBlocks.SNAIL_SHELL);
	public static final RegistryObject<Item> PEAT = block(ForestModBlocks.PEAT);
	public static final RegistryObject<Item> CRUSHED_SANDSTONE = block(ForestModBlocks.CRUSHED_SANDSTONE);
	public static final RegistryObject<Item> CRUSHED_SANDSTONE_STAIRS = block(ForestModBlocks.CRUSHED_SANDSTONE_STAIRS);
	public static final RegistryObject<Item> CRUSHED_SANDSTONE_SLAB = block(ForestModBlocks.CRUSHED_SANDSTONE_SLAB);
	public static final RegistryObject<Item> CRUSHED_SANDSTONE_WALL = block(ForestModBlocks.CRUSHED_SANDSTONE_WALL);
	public static final RegistryObject<Item> RED_CRUSHED_SANDSTONE = block(ForestModBlocks.RED_CRUSHED_SANDSTONE);
	public static final RegistryObject<Item> RED_CRUSHED_SANDSTONE_STAIRS = block(ForestModBlocks.RED_CRUSHED_SANDSTONE_STAIRS);
	public static final RegistryObject<Item> RED_CRUSHED_SANDSTONE_SLAB = block(ForestModBlocks.RED_CRUSHED_SANDSTONE_SLAB);
	public static final RegistryObject<Item> RED_CRUSHED_SANDSTONE_WALL = block(ForestModBlocks.RED_CRUSHED_SANDSTONE_WALL);
	public static final RegistryObject<Item> OAK_PARQUET = block(ForestModBlocks.OAK_PARQUET);
	public static final RegistryObject<Item> BIRCH_PARQUET = block(ForestModBlocks.BIRCH_PARQUET);
	public static final RegistryObject<Item> DARK_OAK_PARQUET = block(ForestModBlocks.DARK_OAK_PARQUET);
	public static final RegistryObject<Item> SPRUCE_PARQUET = block(ForestModBlocks.SPRUCE_PARQUET);
	public static final RegistryObject<Item> ACACIA_PARQUET = block(ForestModBlocks.ACACIA_PARQUET);
	public static final RegistryObject<Item> TROPICAL_PARQUET = block(ForestModBlocks.TROPICAL_PARQUET);
	public static final RegistryObject<Item> CRIMSON_PARQUET = block(ForestModBlocks.CRIMSON_PARQUET);
	public static final RegistryObject<Item> WARPED_PARQUET = block(ForestModBlocks.WARPED_PARQUET);
	public static final RegistryObject<Item> MANGROVE_PARQUET = block(ForestModBlocks.MANGROVE_PARQUET);
	public static final RegistryObject<Item> CHERRY_PARQUET = block(ForestModBlocks.CHERRY_PARQUET);
	public static final RegistryObject<Item> MULBERRY_PARQUET = block(ForestModBlocks.MULBERRY_PARQUET);
	public static final RegistryObject<Item> MARBLE = block(ForestModBlocks.MARBLE);
	public static final RegistryObject<Item> MARBLE_BRICKS = block(ForestModBlocks.MARBLE_BRICKS);
	public static final RegistryObject<Item> POLISHED_MARBLE = block(ForestModBlocks.POLISHED_MARBLE);
	public static final RegistryObject<Item> POLISHED_MARBLE_SLAB = block(ForestModBlocks.POLISHED_MARBLE_SLAB);
	public static final RegistryObject<Item> MARBLE_BRICKS_SLAB = block(ForestModBlocks.MARBLE_BRICKS_SLAB);
	public static final RegistryObject<Item> POLISHED_MARBLE_STAIRS = block(ForestModBlocks.POLISHED_MARBLE_STAIRS);
	public static final RegistryObject<Item> MARBLE_BRICKS_STAIRS = block(ForestModBlocks.MARBLE_BRICKS_STAIRS);
	public static final RegistryObject<Item> POLISHED_MARBLE_WALL = block(ForestModBlocks.POLISHED_MARBLE_WALL);
	public static final RegistryObject<Item> MARBLE_BRICKS_WALL = block(ForestModBlocks.MARBLE_BRICKS_WALL);
	public static final RegistryObject<Item> RHYOLITE = block(ForestModBlocks.RHYOLITE);
	public static final RegistryObject<Item> POLISHED_RHYOLITE = block(ForestModBlocks.POLISHED_RHYOLITE);
	public static final RegistryObject<Item> RHYOLITE_BRICKS = block(ForestModBlocks.RHYOLITE_BRICKS);
	public static final RegistryObject<Item> CHISELED_RHYOLITE = block(ForestModBlocks.CHISELED_RHYOLITE);
	public static final RegistryObject<Item> RHYOLITE_SLAB = block(ForestModBlocks.RHYOLITE_SLAB);
	public static final RegistryObject<Item> POLISHED_RHYOLITE_SLAB = block(ForestModBlocks.POLISHED_RHYOLITE_SLAB);
	public static final RegistryObject<Item> RHYOLITE_BRICKS_SLAB = block(ForestModBlocks.RHYOLITE_BRICKS_SLAB);
	public static final RegistryObject<Item> RHYOLITE_STAIRS = block(ForestModBlocks.RHYOLITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_RHYOLITE_STAIRS = block(ForestModBlocks.POLISHED_RHYOLITE_STAIRS);
	public static final RegistryObject<Item> RHYOLITE_BRICKS_STAIRS = block(ForestModBlocks.RHYOLITE_BRICKS_STAIRS);
	public static final RegistryObject<Item> RHYOLITE_WALL = block(ForestModBlocks.RHYOLITE_WALL);
	public static final RegistryObject<Item> POLISHED_RHYOLITE_WALL = block(ForestModBlocks.POLISHED_RHYOLITE_WALL);
	public static final RegistryObject<Item> RHYOLITE_BRICKS_WALL = block(ForestModBlocks.RHYOLITE_BRICKS_WALL);
	public static final RegistryObject<Item> ASH_COVER = block(ForestModBlocks.ASH_COVER);
	public static final RegistryObject<Item> ASH_BLOCK = block(ForestModBlocks.ASH_BLOCK);
	public static final RegistryObject<Item> PUMICE = block(ForestModBlocks.PUMICE);
	public static final RegistryObject<Item> POLISHED_PUMICE = block(ForestModBlocks.POLISHED_PUMICE);
	public static final RegistryObject<Item> PUMICE_BRICKS = block(ForestModBlocks.PUMICE_BRICKS);
	public static final RegistryObject<Item> TRUNCATED_PUMICE = block(ForestModBlocks.TRUNCATED_PUMICE);
	public static final RegistryObject<Item> TRUNCATED_CARVED_PUMICE = block(ForestModBlocks.TRUNCATED_CARVED_PUMICE);
	public static final RegistryObject<Item> PUMICE_SLAB = block(ForestModBlocks.PUMICE_SLAB);
	public static final RegistryObject<Item> POLISHED_PUMICE_SLAB = block(ForestModBlocks.POLISHED_PUMICE_SLAB);
	public static final RegistryObject<Item> PUMICE_BRICKS_SLAB = block(ForestModBlocks.PUMICE_BRICKS_SLAB);
	public static final RegistryObject<Item> TRUNCATED_PUMICE_SLAB = block(ForestModBlocks.TRUNCATED_PUMICE_SLAB);
	public static final RegistryObject<Item> PUMICE_STAIRS = block(ForestModBlocks.PUMICE_STAIRS);
	public static final RegistryObject<Item> POLISHED_PUMICE_STAIRS = block(ForestModBlocks.POLISHED_PUMICE_STAIRS);
	public static final RegistryObject<Item> PUMICE_BRICKS_STAIRS = block(ForestModBlocks.PUMICE_BRICKS_STAIRS);
	public static final RegistryObject<Item> TRUNCATED_PUMICE_STAIRS = block(ForestModBlocks.TRUNCATED_PUMICE_STAIRS);
	public static final RegistryObject<Item> PUMICE_WALL = block(ForestModBlocks.PUMICE_WALL);
	public static final RegistryObject<Item> POLISHED_PUMICE_WALL = block(ForestModBlocks.POLISHED_PUMICE_WALL);
	public static final RegistryObject<Item> PUMICE_BRICKS_WALL = block(ForestModBlocks.PUMICE_BRICKS_WALL);
	public static final RegistryObject<Item> TRUNCATED_PUMICE_WALL = block(ForestModBlocks.TRUNCATED_PUMICE_WALL);
	public static final RegistryObject<Item> SANDSLATE = block(ForestModBlocks.SANDSLATE);
	public static final RegistryObject<Item> COBBLED_SANDSLATE = block(ForestModBlocks.COBBLED_SANDSLATE);
	public static final RegistryObject<Item> POLISHED_SANDSLATE = block(ForestModBlocks.POLISHED_SANDSLATE);
	public static final RegistryObject<Item> SANDSLATE_BRICKS = block(ForestModBlocks.SANDSLATE_BRICKS);
	public static final RegistryObject<Item> SANDSLATE_FACETED_BRICKS = block(ForestModBlocks.SANDSLATE_FACETED_BRICKS);
	public static final RegistryObject<Item> COBBLED_SANDSLATE_SLAB = block(ForestModBlocks.COBBLED_SANDSLATE_SLAB);
	public static final RegistryObject<Item> POLISHED_SANDSLATE_SLAB = block(ForestModBlocks.POLISHED_SANDSLATE_SLAB);
	public static final RegistryObject<Item> SANDSLATE_BRICKS_SLAB = block(ForestModBlocks.SANDSLATE_BRICKS_SLAB);
	public static final RegistryObject<Item> COBBLED_SANDSLATE_STAIRS = block(ForestModBlocks.COBBLED_SANDSLATE_STAIRS);
	public static final RegistryObject<Item> POLISHED_SANDSLATE_STAIRS = block(ForestModBlocks.POLISHED_SANDSLATE_STAIRS);
	public static final RegistryObject<Item> SANDSLATE_BRICKS_STAIRS = block(ForestModBlocks.SANDSLATE_BRICKS_STAIRS);
	public static final RegistryObject<Item> COBBLED_SANDSLATE_WALL = block(ForestModBlocks.COBBLED_SANDSLATE_WALL);
	public static final RegistryObject<Item> POLISHED_SANDSLATE_WALL = block(ForestModBlocks.POLISHED_SANDSLATE_WALL);
	public static final RegistryObject<Item> SANDSLATE_BRICKS_WALL = block(ForestModBlocks.SANDSLATE_BRICKS_WALL);
	public static final RegistryObject<Item> RAW_GINGERBREAD_BLOCK = block(ForestModBlocks.RAW_GINGERBREAD_BLOCK);
	public static final RegistryObject<Item> GINGERBREAD_BLOCK = block(ForestModBlocks.GINGERBREAD_BLOCK);
	public static final RegistryObject<Item> GINGERBREAD_BRICKS = block(ForestModBlocks.GINGERBREAD_BRICKS);
	public static final RegistryObject<Item> WHITE_PLANKS = block(ForestModBlocks.WHITE_PLANKS);
	public static final RegistryObject<Item> LIGHT_GRAY_PLANKS = block(ForestModBlocks.LIGHT_GRAY_PLANKS);
	public static final RegistryObject<Item> GRAY_PLANKS = block(ForestModBlocks.GRAY_PLANKS);
	public static final RegistryObject<Item> BLACK_PLANKS = block(ForestModBlocks.BLACK_PLANKS);
	public static final RegistryObject<Item> BROWN_PLANKS = block(ForestModBlocks.BROWN_PLANKS);
	public static final RegistryObject<Item> RED_PLANKS = block(ForestModBlocks.RED_PLANKS);
	public static final RegistryObject<Item> ORANGE_PLANKS = block(ForestModBlocks.ORANGE_PLANKS);
	public static final RegistryObject<Item> YELLOW_PLANKS = block(ForestModBlocks.YELLOW_PLANKS);
	public static final RegistryObject<Item> LIME_PLANKS = block(ForestModBlocks.LIME_PLANKS);
	public static final RegistryObject<Item> GREEN_PLANKS = block(ForestModBlocks.GREEN_PLANKS);
	public static final RegistryObject<Item> CYAN_PLANKS = block(ForestModBlocks.CYAN_PLANKS);
	public static final RegistryObject<Item> LIGHT_BLUE_PLANKS = block(ForestModBlocks.LIGHT_BLUE_PLANKS);
	public static final RegistryObject<Item> BLUE_PLANKS = block(ForestModBlocks.BLUE_PLANKS);
	public static final RegistryObject<Item> PURPLE_PLANKS = block(ForestModBlocks.PURPLE_PLANKS);
	public static final RegistryObject<Item> MAGENTA_PLANKS = block(ForestModBlocks.MAGENTA_PLANKS);
	public static final RegistryObject<Item> PINK_PLANKS = block(ForestModBlocks.PINK_PLANKS);
	public static final RegistryObject<Item> WHITE_STAIRS = block(ForestModBlocks.WHITE_STAIRS);
	public static final RegistryObject<Item> LIGHT_GRAY_STAIRS = block(ForestModBlocks.LIGHT_GRAY_STAIRS);
	public static final RegistryObject<Item> GRAY_STAIRS = block(ForestModBlocks.GRAY_STAIRS);
	public static final RegistryObject<Item> BLACK_STAIRS = block(ForestModBlocks.BLACK_STAIRS);
	public static final RegistryObject<Item> BROWN_STAIRS = block(ForestModBlocks.BROWN_STAIRS);
	public static final RegistryObject<Item> RED_STAIRS = block(ForestModBlocks.RED_STAIRS);
	public static final RegistryObject<Item> ORANGE_STAIRS = block(ForestModBlocks.ORANGE_STAIRS);
	public static final RegistryObject<Item> YELLOW_STAIRS = block(ForestModBlocks.YELLOW_STAIRS);
	public static final RegistryObject<Item> LIME_STAIRS = block(ForestModBlocks.LIME_STAIRS);
	public static final RegistryObject<Item> GREEN_STAIRS = block(ForestModBlocks.GREEN_STAIRS);
	public static final RegistryObject<Item> CYAN_STAIRS = block(ForestModBlocks.CYAN_STAIRS);
	public static final RegistryObject<Item> LIGHT_BLUE_STAIRS = block(ForestModBlocks.LIGHT_BLUE_STAIRS);
	public static final RegistryObject<Item> BLUE_STAIRS = block(ForestModBlocks.BLUE_STAIRS);
	public static final RegistryObject<Item> PURPLE_STAIRS = block(ForestModBlocks.PURPLE_STAIRS);
	public static final RegistryObject<Item> MAGENTA_STAIRS = block(ForestModBlocks.MAGENTA_STAIRS);
	public static final RegistryObject<Item> PINK_STAIRS = block(ForestModBlocks.PINK_STAIRS);
	public static final RegistryObject<Item> WHITE_SLAB = block(ForestModBlocks.WHITE_SLAB);
	public static final RegistryObject<Item> LIGHT_GRAY_SLAB = block(ForestModBlocks.LIGHT_GRAY_SLAB);
	public static final RegistryObject<Item> GRAY_SLAB = block(ForestModBlocks.GRAY_SLAB);
	public static final RegistryObject<Item> BLACK_SLAB = block(ForestModBlocks.BLACK_SLAB);
	public static final RegistryObject<Item> BROWN_SLAB = block(ForestModBlocks.BROWN_SLAB);
	public static final RegistryObject<Item> RED_SLAB = block(ForestModBlocks.RED_SLAB);
	public static final RegistryObject<Item> ORANGE_SLAB = block(ForestModBlocks.ORANGE_SLAB);
	public static final RegistryObject<Item> YELLOW_SLAB = block(ForestModBlocks.YELLOW_SLAB);
	public static final RegistryObject<Item> LIME_SLAB = block(ForestModBlocks.LIME_SLAB);
	public static final RegistryObject<Item> GREEN_SLAB = block(ForestModBlocks.GREEN_SLAB);
	public static final RegistryObject<Item> CYAN_SLAB = block(ForestModBlocks.CYAN_SLAB);
	public static final RegistryObject<Item> LIGHT_BLUE_SLAB = block(ForestModBlocks.LIGHT_BLUE_SLAB);
	public static final RegistryObject<Item> BLUE_SLAB = block(ForestModBlocks.BLUE_SLAB);
	public static final RegistryObject<Item> PURPLE_SLAB = block(ForestModBlocks.PURPLE_SLAB);
	public static final RegistryObject<Item> MAGENTA_SLAB = block(ForestModBlocks.MAGENTA_SLAB);
	public static final RegistryObject<Item> PINK_SLAB = block(ForestModBlocks.PINK_SLAB);
	public static final RegistryObject<Item> WHITE_FENCE = block(ForestModBlocks.WHITE_FENCE);
	public static final RegistryObject<Item> LIGHT_GRAY_FENCE = block(ForestModBlocks.LIGHT_GRAY_FENCE);
	public static final RegistryObject<Item> GRAY_FENCE = block(ForestModBlocks.GRAY_FENCE);
	public static final RegistryObject<Item> BLACK_FENCE = block(ForestModBlocks.BLACK_FENCE);
	public static final RegistryObject<Item> BROWN_FENCE = block(ForestModBlocks.BROWN_FENCE);
	public static final RegistryObject<Item> RED_FENCE = block(ForestModBlocks.RED_FENCE);
	public static final RegistryObject<Item> ORANGE_FENCE = block(ForestModBlocks.ORANGE_FENCE);
	public static final RegistryObject<Item> YELLOW_FENCE = block(ForestModBlocks.YELLOW_FENCE);
	public static final RegistryObject<Item> LIME_FENCE = block(ForestModBlocks.LIME_FENCE);
	public static final RegistryObject<Item> GREEN_FENCE = block(ForestModBlocks.GREEN_FENCE);
	public static final RegistryObject<Item> CYAN_FENCE = block(ForestModBlocks.CYAN_FENCE);
	public static final RegistryObject<Item> LIGHT_BLUE_FENCE = block(ForestModBlocks.LIGHT_BLUE_FENCE);
	public static final RegistryObject<Item> BLUE_FENCE = block(ForestModBlocks.BLUE_FENCE);
	public static final RegistryObject<Item> PURPLE_FENCE = block(ForestModBlocks.PURPLE_FENCE);
	public static final RegistryObject<Item> MAGENTA_FENCE = block(ForestModBlocks.MAGENTA_FENCE);
	public static final RegistryObject<Item> PINK_FENCE = block(ForestModBlocks.PINK_FENCE);
	public static final RegistryObject<Item> WHITE_FENCE_GATE = block(ForestModBlocks.WHITE_FENCE_GATE);
	public static final RegistryObject<Item> LIGHT_GRAY_FENCE_GATE = block(ForestModBlocks.LIGHT_GRAY_FENCE_GATE);
	public static final RegistryObject<Item> GRAY_FENCE_GATE = block(ForestModBlocks.GRAY_FENCE_GATE);
	public static final RegistryObject<Item> BLACK_FENCE_GATE = block(ForestModBlocks.BLACK_FENCE_GATE);
	public static final RegistryObject<Item> BROWN_FENCE_GATE = block(ForestModBlocks.BROWN_FENCE_GATE);
	public static final RegistryObject<Item> RED_FENCE_GATE = block(ForestModBlocks.RED_FENCE_GATE);
	public static final RegistryObject<Item> ORANGE_FENCE_GATE = block(ForestModBlocks.ORANGE_FENCE_GATE);
	public static final RegistryObject<Item> YELLOW_FENCE_GATE = block(ForestModBlocks.YELLOW_FENCE_GATE);
	public static final RegistryObject<Item> LIME_FENCE_GATE = block(ForestModBlocks.LIME_FENCE_GATE);
	public static final RegistryObject<Item> GREEN_FENCE_GATE = block(ForestModBlocks.GREEN_FENCE_GATE);
	public static final RegistryObject<Item> CYAN_FENCE_GATE = block(ForestModBlocks.CYAN_FENCE_GATE);
	public static final RegistryObject<Item> LIGHT_BLUE_FENCE_GATE = block(ForestModBlocks.LIGHT_BLUE_FENCE_GATE);
	public static final RegistryObject<Item> BLUE_FENCE_GATE = block(ForestModBlocks.BLUE_FENCE_GATE);
	public static final RegistryObject<Item> PURPLE_FENCE_GATE = block(ForestModBlocks.PURPLE_FENCE_GATE);
	public static final RegistryObject<Item> MAGENTA_FENCE_GATE = block(ForestModBlocks.MAGENTA_FENCE_GATE);
	public static final RegistryObject<Item> PINK_FENCE_GATE = block(ForestModBlocks.PINK_FENCE_GATE);
	public static final RegistryObject<Item> GRAPE = REGISTRY.register("grape", () -> new GrapeItem());
	public static final RegistryObject<Item> BLUEBERRY = REGISTRY.register("blueberry", () -> new BlueberryItem());
	public static final RegistryObject<Item> LETTUCE = REGISTRY.register("lettuce", () -> new LettuceItem());
	public static final RegistryObject<Item> RAW_BARBECUE = REGISTRY.register("raw_barbecue", () -> new RawBarbecueItem());
	public static final RegistryObject<Item> BARBECUE = REGISTRY.register("barbecue", () -> new BarbecueItem());
	public static final RegistryObject<Item> MEAT_LOAF = REGISTRY.register("meat_loaf", () -> new MeatLoafItem());
	public static final RegistryObject<Item> LARD = REGISTRY.register("lard", () -> new LardItem());
	public static final RegistryObject<Item> BREADWITHLARD = REGISTRY.register("breadwithlard", () -> new BreadwithlardItem());
	public static final RegistryObject<Item> BERRY_STRUDEL = REGISTRY.register("berry_strudel", () -> new BerryStrudelItem());
	public static final RegistryObject<Item> GINGERBREAD_DOUGH = REGISTRY.register("gingerbread_dough", () -> new GingerbreadDoughItem());
	public static final RegistryObject<Item> RAW_GINGERBREAD_MAN = REGISTRY.register("raw_gingerbread_man", () -> new RawGingerbreadManItem());
	public static final RegistryObject<Item> RAW_GINGERBREAD_HEART = REGISTRY.register("raw_gingerbread_heart", () -> new RawGingerbreadHeartItem());
	public static final RegistryObject<Item> RAW_GINGERBREAD_BRICK = REGISTRY.register("raw_gingerbread_brick", () -> new RawGingerbreadBrickItem());
	public static final RegistryObject<Item> RAW_GINGERBREAD_PINE = REGISTRY.register("raw_gingerbread_pine", () -> new RawGingerbreadPineItem());
	public static final RegistryObject<Item> GINGERBREAD_MAN = REGISTRY.register("gingerbread_man", () -> new GingerbreadManItem());
	public static final RegistryObject<Item> GLAZED_GINGERBREAD_MEN = REGISTRY.register("glazed_gingerbread_men", () -> new GlazedGingerbreadMenItem());
	public static final RegistryObject<Item> GINGERBREAD_HEART = REGISTRY.register("gingerbread_heart", () -> new GingerbreadHeartItem());
	public static final RegistryObject<Item> GINGERBREAD_BRICK = REGISTRY.register("gingerbread_brick", () -> new GingerbreadBrickItem());
	public static final RegistryObject<Item> GINGERBREAD_ROUND = REGISTRY.register("gingerbread_round", () -> new GingerbreadRoundItem());
	public static final RegistryObject<Item> GINGERBREAD_PINE = REGISTRY.register("gingerbread_pine", () -> new GingerbreadPineItem());
	public static final RegistryObject<Item> GLAZED_GINGERBREAD_PINE = REGISTRY.register("glazed_gingerbread_pine", () -> new GlazedGingerbreadPineItem());
	public static final RegistryObject<Item> WINE = REGISTRY.register("wine", () -> new WineItem());
	public static final RegistryObject<Item> PEAT_PIECE = REGISTRY.register("peat_piece", () -> new PeatPieceItem());
	public static final RegistryObject<Item> GINGERBREAD_FORM_MAN = REGISTRY.register("gingerbread_form_man", () -> new GingerbreadFormManItem());
	public static final RegistryObject<Item> GINGERBREAD_FORM_HEART = REGISTRY.register("gingerbread_form_heart", () -> new GingerbreadFormHeartItem());
	public static final RegistryObject<Item> GINGERBREAD_FORM_BRICK = REGISTRY.register("gingerbread_form_brick", () -> new GingerbreadFormBrickItem());
	public static final RegistryObject<Item> GINGERBREAD_FORM_PINE = REGISTRY.register("gingerbread_form_pine", () -> new GingerbreadFormPineItem());
	public static final RegistryObject<Item> MUSIC_DISC_STROFA = REGISTRY.register("music_disc_strofa", () -> new MusicDiscStrofaItem());
	public static final RegistryObject<Item> RACOON_SPAWN_EGG = REGISTRY.register("racoon_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.RACOON, -10066330, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> BROWN_BEAR_SPAWN_EGG = REGISTRY.register("brown_bear_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.BROWN_BEAR, -13434880, -6737152, new Item.Properties()));
	public static final RegistryObject<Item> SNAIL_SPAWN_EGG = REGISTRY.register("snail_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.SNAIL, -6724096, -13434880, new Item.Properties()));
	public static final RegistryObject<Item> FENNEC_SPAWN_EGG = REGISTRY.register("fennec_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.FENNEC, -26317, -3368704, new Item.Properties()));
	public static final RegistryObject<Item> FIRE_SALAMANDER_SPAWN_EGG = REGISTRY.register("fire_salamander_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.FIRE_SALAMANDER, -13261, -16777216, new Item.Properties()));
	public static final RegistryObject<Item> LETTUCE_SEED = REGISTRY.register("lettuce_seed", () -> new LettuceSeedItem());
	public static final RegistryObject<Item> WILDFLOWER = block(ForestModBlocks.WILDFLOWER);
	public static final RegistryObject<Item> BURNING_BLOSSOM = block(ForestModBlocks.BURNING_BLOSSOM);
	public static final RegistryObject<Item> LAVANDER = block(ForestModBlocks.LAVANDER);
	public static final RegistryObject<Item> DESERT_ROSE = block(ForestModBlocks.DESERT_ROSE);
	public static final RegistryObject<Item> BLUE_ROSE = block(ForestModBlocks.BLUE_ROSE);
	public static final RegistryObject<Item> SUNSHROOM = block(ForestModBlocks.SUNSHROOM);
	public static final RegistryObject<Item> MOONSHROOM = block(ForestModBlocks.MOONSHROOM);
	public static final RegistryObject<Item> GRAPE_VINE_0 = block(ForestModBlocks.GRAPE_VINE_0);
	public static final RegistryObject<Item> WHITE_ROSE_BUSH = doubleBlock(ForestModBlocks.WHITE_ROSE_BUSH);
	public static final RegistryObject<Item> PINK_ROSE_BUSH = doubleBlock(ForestModBlocks.PINK_ROSE_BUSH);
	public static final RegistryObject<Item> SILVER_ORE = block(ForestModBlocks.SILVER_ORE);
	public static final RegistryObject<Item> DEEPSLATE_SILVER_ORE = block(ForestModBlocks.DEEPSLATE_SILVER_ORE);
	public static final RegistryObject<Item> RAW_SILVER_BLOCK = block(ForestModBlocks.RAW_SILVER_BLOCK);
	public static final RegistryObject<Item> SILVER_BLOCK = block(ForestModBlocks.SILVER_BLOCK);
	public static final RegistryObject<Item> RAW_SILVER = REGISTRY.register("raw_silver", () -> new RawSilverItem());
	public static final RegistryObject<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", () -> new SilverIngotItem());
	public static final RegistryObject<Item> SILVER_NUGGET = REGISTRY.register("silver_nugget", () -> new SilverNuggetItem());
	public static final RegistryObject<Item> SILVER_AXE = REGISTRY.register("silver_axe", () -> new SilverAxeItem());
	public static final RegistryObject<Item> SILVER_PICKAXE = REGISTRY.register("silver_pickaxe", () -> new SilverPickaxeItem());
	public static final RegistryObject<Item> SILVER_SHOVEL = REGISTRY.register("silver_shovel", () -> new SilverShovelItem());
	public static final RegistryObject<Item> SILVER_HOE = REGISTRY.register("silver_hoe", () -> new SilverHoeItem());
	public static final RegistryObject<Item> SILVER_SWORD = REGISTRY.register("silver_sword", () -> new SilverSwordItem());
	public static final RegistryObject<Item> SILVER_ARMOR_HELMET = REGISTRY.register("silver_armor_helmet", () -> new SilverArmorItem.Helmet());
	public static final RegistryObject<Item> SILVER_ARMOR_CHESTPLATE = REGISTRY.register("silver_armor_chestplate", () -> new SilverArmorItem.Chestplate());
	public static final RegistryObject<Item> SILVER_ARMOR_LEGGINGS = REGISTRY.register("silver_armor_leggings", () -> new SilverArmorItem.Leggings());
	public static final RegistryObject<Item> SILVER_ARMOR_BOOTS = REGISTRY.register("silver_armor_boots", () -> new SilverArmorItem.Boots());
	public static final RegistryObject<Item> QUIVER = REGISTRY.register("quiver", () -> new QuiverItem());
	public static final RegistryObject<Item> FERMENTATION_BARREL = block(ForestModBlocks.FERMENTATION_BARREL);
	public static final RegistryObject<Item> MULBERRY_SAPLING = block(ForestModBlocks.MULBERRY_SAPLING);
	public static final RegistryObject<Item> MULBERRY_LEAVES_WITHOUT_WHITE = block(ForestModBlocks.MULBERRY_LEAVES_WITHOUT_WHITE);
	public static final RegistryObject<Item> MULBERRY_LEAVES_WITHOUT_BLACK = block(ForestModBlocks.MULBERRY_LEAVES_WITHOUT_BLACK);
	public static final RegistryObject<Item> MULBERRY_LEAVES_WITH_WHITE = block(ForestModBlocks.MULBERRY_LEAVES_WITH_WHITE);
	public static final RegistryObject<Item> MULBERRY_LEAVES_WITH_BLACK = block(ForestModBlocks.MULBERRY_LEAVES_WITH_BLACK);
	public static final RegistryObject<Item> MULBERRY_WOOD = block(ForestModBlocks.MULBERRY_WOOD);
	public static final RegistryObject<Item> MULBERRY_LOG = block(ForestModBlocks.MULBERRY_LOG);
	public static final RegistryObject<Item> STRIPPED_MULBERRY_WOOD = block(ForestModBlocks.STRIPPED_MULBERRY_WOOD);
	public static final RegistryObject<Item> STRIPPED_MULBERRY_LOG = block(ForestModBlocks.STRIPPED_MULBERRY_LOG);
	public static final RegistryObject<Item> MULBERRY_PLANKS = block(ForestModBlocks.MULBERRY_PLANKS);
	public static final RegistryObject<Item> MULBERRY_STAIRS = block(ForestModBlocks.MULBERRY_STAIRS);
	public static final RegistryObject<Item> MULBERRY_SLAB = block(ForestModBlocks.MULBERRY_SLAB);
	public static final RegistryObject<Item> MULBERRY_PRESSURE_PLATE = block(ForestModBlocks.MULBERRY_PRESSURE_PLATE);
	public static final RegistryObject<Item> MULBERRY_BUTTON = block(ForestModBlocks.MULBERRY_BUTTON);
	public static final RegistryObject<Item> MULBERRY_DOOR = doubleBlock(ForestModBlocks.MULBERRY_DOOR);
	public static final RegistryObject<Item> MULBERRY_TRAPDOOR = block(ForestModBlocks.MULBERRY_TRAPDOOR);
	public static final RegistryObject<Item> MULBERRY_FENCE = block(ForestModBlocks.MULBERRY_FENCE);
	public static final RegistryObject<Item> MULBERRY_FENCE_GATE = block(ForestModBlocks.MULBERRY_FENCE_GATE);
	public static final RegistryObject<Item> SAPPHIRE = REGISTRY.register("sapphire", () -> new SapphireItem());
	public static final RegistryObject<Item> SAPPHIRE_ORE = block(ForestModBlocks.SAPPHIRE_ORE);
	public static final RegistryObject<Item> SAPPHIRE_BLOCK = block(ForestModBlocks.SAPPHIRE_BLOCK);
	public static final RegistryObject<Item> DEEPSLATE_SAPPHIRE_ORE = block(ForestModBlocks.DEEPSLATE_SAPPHIRE_ORE);
	public static final RegistryObject<Item> DENSE_WEB = block(ForestModBlocks.DENSE_WEB);
	public static final RegistryObject<Item> DENSE_WEB_WITH_SPIDER = block(ForestModBlocks.DENSE_WEB_WITH_SPIDER);
	public static final RegistryObject<Item> BLUEBERRY_BUSH_0 = block(ForestModBlocks.BLUEBERRY_BUSH_0);
	public static final RegistryObject<Item> BLUEBERRY_BUSH_1 = block(ForestModBlocks.BLUEBERRY_BUSH_1);
	public static final RegistryObject<Item> LETTUCE_STAGE_0 = block(ForestModBlocks.LETTUCE_STAGE_0);
	public static final RegistryObject<Item> LETTUCE_STAGE_1 = block(ForestModBlocks.LETTUCE_STAGE_1);
	public static final RegistryObject<Item> LETTUCE_STAGE_2 = block(ForestModBlocks.LETTUCE_STAGE_2);
	public static final RegistryObject<Item> LETTUCE_STAGE_3 = block(ForestModBlocks.LETTUCE_STAGE_3);
	public static final RegistryObject<Item> GINGERBREAD_FORM_COCK = REGISTRY.register("gingerbread_form_cock", () -> new GingerbreadFormCockItem());
	public static final RegistryObject<Item> GINGERBREAD_COCK = REGISTRY.register("gingerbread_cock", () -> new GingerbreadCockItem());
	public static final RegistryObject<Item> RAW_GINGERBREAD_COCK = REGISTRY.register("raw_gingerbread_cock", () -> new RawGingerbreadCockItem());
	public static final RegistryObject<Item> EUCALYPTUS_WOOD = block(ForestModBlocks.EUCALYPTUS_WOOD);
	public static final RegistryObject<Item> EUCALYPTUS_LOG = block(ForestModBlocks.EUCALYPTUS_LOG);
	public static final RegistryObject<Item> EUCALYPTUS_PLANKS = block(ForestModBlocks.EUCALYPTUS_PLANKS);
	public static final RegistryObject<Item> EUCALYPTUS_LEAVES = block(ForestModBlocks.EUCALYPTUS_LEAVES);
	public static final RegistryObject<Item> EUCALYPTUS_STAIRS = block(ForestModBlocks.EUCALYPTUS_STAIRS);
	public static final RegistryObject<Item> EUCALYPTUS_SLAB = block(ForestModBlocks.EUCALYPTUS_SLAB);
	public static final RegistryObject<Item> EUCALYPTUS_FENCE = block(ForestModBlocks.EUCALYPTUS_FENCE);
	public static final RegistryObject<Item> EUCALYPTUS_FENCE_GATE = block(ForestModBlocks.EUCALYPTUS_FENCE_GATE);
	public static final RegistryObject<Item> EUCALYPTUS_PRESSURE_PLATE = block(ForestModBlocks.EUCALYPTUS_PRESSURE_PLATE);
	public static final RegistryObject<Item> EUCALYPTUS_BUTTON = block(ForestModBlocks.EUCALYPTUS_BUTTON);
	public static final RegistryObject<Item> STRIPPED_EUCALYPTUS_WOOD = block(ForestModBlocks.STRIPPED_EUCALYPTUS_WOOD);
	public static final RegistryObject<Item> STRIPPED_EUCALYPTUS_LOG = block(ForestModBlocks.STRIPPED_EUCALYPTUS_LOG);
	public static final RegistryObject<Item> EUCALYPTUS_PARQUET = block(ForestModBlocks.EUCALYPTUS_PARQUET);
	public static final RegistryObject<Item> EUCALYPTUS_DOOR = doubleBlock(ForestModBlocks.EUCALYPTUS_DOOR);
	public static final RegistryObject<Item> EUCALYPTUS_TRAPDOOR = block(ForestModBlocks.EUCALYPTUS_TRAPDOOR);
	public static final RegistryObject<Item> EUCALYPTUS_SAPLING = block(ForestModBlocks.EUCALYPTUS_SAPLING);
	public static final RegistryObject<Item> GRAPE_VINE_1 = block(ForestModBlocks.GRAPE_VINE_1);
	public static final RegistryObject<Item> BROWN_BEAR_ARMOR_HELMET = REGISTRY.register("brown_bear_armor_helmet", () -> new BrownBearArmorItem.Helmet());
	public static final RegistryObject<Item> BROWN_BEAR_ARMOR_CHESTPLATE = REGISTRY.register("brown_bear_armor_chestplate", () -> new BrownBearArmorItem.Chestplate());
	public static final RegistryObject<Item> BROWN_BEAR_ARMOR_LEGGINGS = REGISTRY.register("brown_bear_armor_leggings", () -> new BrownBearArmorItem.Leggings());
	public static final RegistryObject<Item> BROWN_BEAR_ARMOR_BOOTS = REGISTRY.register("brown_bear_armor_boots", () -> new BrownBearArmorItem.Boots());
	public static final RegistryObject<Item> POLAR_BEAR_ARMOR_HELMET = REGISTRY.register("polar_bear_armor_helmet", () -> new PolarBearArmorItem.Helmet());
	public static final RegistryObject<Item> POLAR_BEAR_ARMOR_CHESTPLATE = REGISTRY.register("polar_bear_armor_chestplate", () -> new PolarBearArmorItem.Chestplate());
	public static final RegistryObject<Item> POLAR_BEAR_ARMOR_LEGGINGS = REGISTRY.register("polar_bear_armor_leggings", () -> new PolarBearArmorItem.Leggings());
	public static final RegistryObject<Item> POLAR_BEAR_ARMOR_BOOTS = REGISTRY.register("polar_bear_armor_boots", () -> new PolarBearArmorItem.Boots());
	public static final RegistryObject<Item> BROWN_BEAR_CARPET = block(ForestModBlocks.BROWN_BEAR_CARPET);
	public static final RegistryObject<Item> POLAR_BEAR_CARPET = block(ForestModBlocks.POLAR_BEAR_CARPET);
	public static final RegistryObject<Item> BROWN_BEAR_PELT = REGISTRY.register("brown_bear_pelt", () -> new BrownBearPeltItem());
	public static final RegistryObject<Item> POLAR_BEAR_PELT = REGISTRY.register("polar_bear_pelt", () -> new PolarBearPeltItem());
	public static final RegistryObject<Item> BLACK_MULBERRY = REGISTRY.register("black_mulberry", () -> new BlackMulberryItem());
	public static final RegistryObject<Item> WHITE_MULBERRY = REGISTRY.register("white_mulberry", () -> new WhiteMulberryItem());
	public static final RegistryObject<Item> ORANGE_BUTTERFLY_SPAWN_EGG = REGISTRY.register("orange_butterfly_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.ORANGE_BUTTERFLY, -39424, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> PINK_BUTTERFLY_SPAWN_EGG = REGISTRY.register("pink_butterfly_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.PINK_BUTTERFLY, -26164, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> BLUE_BUTTERFLY_SPAWN_EGG = REGISTRY.register("blue_butterfly_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.BLUE_BUTTERFLY, -16724737, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> GREEN_BUTTERFLY_SPAWN_EGG = REGISTRY.register("green_butterfly_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.GREEN_BUTTERFLY, -13382656, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> PURPLE_BUTTERFLY_SPAWN_EGG = REGISTRY.register("purple_butterfly_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.PURPLE_BUTTERFLY, -3407617, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> CALIBRI_SPAWN_EGG = REGISTRY.register("calibri_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.CALIBRI, -16738048, -16737844, new Item.Properties()));
	public static final RegistryObject<Item> CALIBRI_FEATHER = REGISTRY.register("calibri_feather", () -> new CalibriFeatherItem());
	public static final RegistryObject<Item> DART = REGISTRY.register("dart", () -> new DartItem());
	public static final RegistryObject<Item> VULTURE_SPAWN_EGG = REGISTRY.register("vulture_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.VULTURE, -10079488, -6750157, new Item.Properties()));
	public static final RegistryObject<Item> RASPBERRY = REGISTRY.register("raspberry", () -> new RaspberryItem());
	public static final RegistryObject<Item> RASPBERRY_BUSH_0 = block(ForestModBlocks.RASPBERRY_BUSH_0);
	public static final RegistryObject<Item> RASPBERRY_BUSH_1 = block(ForestModBlocks.RASPBERRY_BUSH_1);
	public static final RegistryObject<Item> RASPBERRY_BUSH_2 = block(ForestModBlocks.RASPBERRY_BUSH_2);
	public static final RegistryObject<Item> RASPBERRY_BUSH_3 = block(ForestModBlocks.RASPBERRY_BUSH_3);
	public static final RegistryObject<Item> SARBAKAN = REGISTRY.register("sarbakan", () -> new SarbakanItem());
	public static final RegistryObject<Item> RAT_SPAWN_EGG = REGISTRY.register("rat_spawn_egg", () -> new ForgeSpawnEggItem(ForestModEntities.RAT, -10066330, -26215, new Item.Properties()));
	public static final RegistryObject<Item> CATTAIL = doubleBlock(ForestModBlocks.CATTAIL);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
