
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package ru.power_umc.forestxreborn.init;

import ru.power_umc.forestxreborn.block.YellowStairsBlock;
import ru.power_umc.forestxreborn.block.YellowSlabBlock;
import ru.power_umc.forestxreborn.block.YellowPlanksBlock;
import ru.power_umc.forestxreborn.block.YellowFenceGateBlock;
import ru.power_umc.forestxreborn.block.YellowFenceBlock;
import ru.power_umc.forestxreborn.block.WildflowerBlock;
import ru.power_umc.forestxreborn.block.WhiteStairsBlock;
import ru.power_umc.forestxreborn.block.WhiteSlabBlock;
import ru.power_umc.forestxreborn.block.WhiteRoseBushBlock;
import ru.power_umc.forestxreborn.block.WhitePlanksBlock;
import ru.power_umc.forestxreborn.block.WhiteFenceGateBlock;
import ru.power_umc.forestxreborn.block.WhiteFenceBlock;
import ru.power_umc.forestxreborn.block.WeatheredCopperLadderBlock;
import ru.power_umc.forestxreborn.block.WaxedWeatheredCopperLadderBlock;
import ru.power_umc.forestxreborn.block.WaxedOxidizedCopperLadderBlock;
import ru.power_umc.forestxreborn.block.WaxedExposedCopperLadderBlock;
import ru.power_umc.forestxreborn.block.WaxedCopperLadderBlock;
import ru.power_umc.forestxreborn.block.WarpedParquetBlock;
import ru.power_umc.forestxreborn.block.TruncatedPumiceWallBlock;
import ru.power_umc.forestxreborn.block.TruncatedPumiceStairsBlock;
import ru.power_umc.forestxreborn.block.TruncatedPumiceSlabBlock;
import ru.power_umc.forestxreborn.block.TruncatedPumiceBlock;
import ru.power_umc.forestxreborn.block.TruncatedCarvedPumiceBlock;
import ru.power_umc.forestxreborn.block.TropicalParquetBlock;
import ru.power_umc.forestxreborn.block.SunshroomBlock;
import ru.power_umc.forestxreborn.block.StrippedMulberryWoodBlock;
import ru.power_umc.forestxreborn.block.StrippedMulberryLogBlock;
import ru.power_umc.forestxreborn.block.StrippedEucalyptusWoodBlock;
import ru.power_umc.forestxreborn.block.StrippedEucalyptusLogBlock;
import ru.power_umc.forestxreborn.block.SpruceParquetBlock;
import ru.power_umc.forestxreborn.block.SnailShellBlock;
import ru.power_umc.forestxreborn.block.SilverOreBlock;
import ru.power_umc.forestxreborn.block.SilverBlockBlock;
import ru.power_umc.forestxreborn.block.SapphireOreBlock;
import ru.power_umc.forestxreborn.block.SapphireBlockBlock;
import ru.power_umc.forestxreborn.block.SandslateFacetedBricksBlock;
import ru.power_umc.forestxreborn.block.SandslateBricksWallBlock;
import ru.power_umc.forestxreborn.block.SandslateBricksStairsBlock;
import ru.power_umc.forestxreborn.block.SandslateBricksSlabBlock;
import ru.power_umc.forestxreborn.block.SandslateBricksBlock;
import ru.power_umc.forestxreborn.block.SandslateBlock;
import ru.power_umc.forestxreborn.block.RyeStage7Block;
import ru.power_umc.forestxreborn.block.RyeStage6Block;
import ru.power_umc.forestxreborn.block.RyeStage5Block;
import ru.power_umc.forestxreborn.block.RyeStage4Block;
import ru.power_umc.forestxreborn.block.RyeStage3Block;
import ru.power_umc.forestxreborn.block.RyeStage2Block;
import ru.power_umc.forestxreborn.block.RyeStage1Block;
import ru.power_umc.forestxreborn.block.RyeStage0Block;
import ru.power_umc.forestxreborn.block.RhyoliteWallBlock;
import ru.power_umc.forestxreborn.block.RhyoliteStairsBlock;
import ru.power_umc.forestxreborn.block.RhyoliteSlabBlock;
import ru.power_umc.forestxreborn.block.RhyoliteBricksWallBlock;
import ru.power_umc.forestxreborn.block.RhyoliteBricksStairsBlock;
import ru.power_umc.forestxreborn.block.RhyoliteBricksSlabBlock;
import ru.power_umc.forestxreborn.block.RhyoliteBricksBlock;
import ru.power_umc.forestxreborn.block.RhyoliteBlock;
import ru.power_umc.forestxreborn.block.RedStairsBlock;
import ru.power_umc.forestxreborn.block.RedSlabBlock;
import ru.power_umc.forestxreborn.block.RedPlanksBlock;
import ru.power_umc.forestxreborn.block.RedFenceGateBlock;
import ru.power_umc.forestxreborn.block.RedFenceBlock;
import ru.power_umc.forestxreborn.block.RedCrushedSandstoneWallBlock;
import ru.power_umc.forestxreborn.block.RedCrushedSandstoneStairsBlock;
import ru.power_umc.forestxreborn.block.RedCrushedSandstoneSlabBlock;
import ru.power_umc.forestxreborn.block.RedCrushedSandstoneBlock;
import ru.power_umc.forestxreborn.block.RawSilverBlockBlock;
import ru.power_umc.forestxreborn.block.RawGingerbreadBlockBlock;
import ru.power_umc.forestxreborn.block.RaspberryBush3Block;
import ru.power_umc.forestxreborn.block.RaspberryBush2Block;
import ru.power_umc.forestxreborn.block.RaspberryBush1Block;
import ru.power_umc.forestxreborn.block.RaspberryBush0Block;
import ru.power_umc.forestxreborn.block.PurpleStairsBlock;
import ru.power_umc.forestxreborn.block.PurpleSlabBlock;
import ru.power_umc.forestxreborn.block.PurplePlanksBlock;
import ru.power_umc.forestxreborn.block.PurpleFenceGateBlock;
import ru.power_umc.forestxreborn.block.PurpleFenceBlock;
import ru.power_umc.forestxreborn.block.PumiceWallBlock;
import ru.power_umc.forestxreborn.block.PumiceStairsBlock;
import ru.power_umc.forestxreborn.block.PumiceSlabBlock;
import ru.power_umc.forestxreborn.block.PumiceBricksWallBlock;
import ru.power_umc.forestxreborn.block.PumiceBricksStairsBlock;
import ru.power_umc.forestxreborn.block.PumiceBricksSlabBlock;
import ru.power_umc.forestxreborn.block.PumiceBricksBlock;
import ru.power_umc.forestxreborn.block.PumiceBlock;
import ru.power_umc.forestxreborn.block.PolishedSandslateWallBlock;
import ru.power_umc.forestxreborn.block.PolishedSandslateStairsBlock;
import ru.power_umc.forestxreborn.block.PolishedSandslateSlabBlock;
import ru.power_umc.forestxreborn.block.PolishedSandslateBlock;
import ru.power_umc.forestxreborn.block.PolishedRhyoliteWallBlock;
import ru.power_umc.forestxreborn.block.PolishedRhyoliteStairsBlock;
import ru.power_umc.forestxreborn.block.PolishedRhyoliteSlabBlock;
import ru.power_umc.forestxreborn.block.PolishedRhyoliteBlock;
import ru.power_umc.forestxreborn.block.PolishedPumiceWallBlock;
import ru.power_umc.forestxreborn.block.PolishedPumiceStairsBlock;
import ru.power_umc.forestxreborn.block.PolishedPumiceSlabBlock;
import ru.power_umc.forestxreborn.block.PolishedPumiceBlock;
import ru.power_umc.forestxreborn.block.PolishedMarbleWallBlock;
import ru.power_umc.forestxreborn.block.PolishedMarbleStairsBlock;
import ru.power_umc.forestxreborn.block.PolishedMarbleSlabBlock;
import ru.power_umc.forestxreborn.block.PolishedMarbleBlock;
import ru.power_umc.forestxreborn.block.PolarBearCarpetBlock;
import ru.power_umc.forestxreborn.block.PinkishMarbleBlock;
import ru.power_umc.forestxreborn.block.PinkStairsBlock;
import ru.power_umc.forestxreborn.block.PinkSlabBlock;
import ru.power_umc.forestxreborn.block.PinkRoseBushBlock;
import ru.power_umc.forestxreborn.block.PinkPlanksBlock;
import ru.power_umc.forestxreborn.block.PinkFenceGateBlock;
import ru.power_umc.forestxreborn.block.PinkFenceBlock;
import ru.power_umc.forestxreborn.block.PeatBlock;
import ru.power_umc.forestxreborn.block.OxidizedCopperLadderBlock;
import ru.power_umc.forestxreborn.block.OrangeStairsBlock;
import ru.power_umc.forestxreborn.block.OrangeSlabBlock;
import ru.power_umc.forestxreborn.block.OrangePlanksBlock;
import ru.power_umc.forestxreborn.block.OrangeFenceGateBlock;
import ru.power_umc.forestxreborn.block.OrangeFenceBlock;
import ru.power_umc.forestxreborn.block.OakParquetBlock;
import ru.power_umc.forestxreborn.block.MulberryWoodBlock;
import ru.power_umc.forestxreborn.block.MulberryTrapdoorBlock;
import ru.power_umc.forestxreborn.block.MulberryStairsBlock;
import ru.power_umc.forestxreborn.block.MulberrySlabBlock;
import ru.power_umc.forestxreborn.block.MulberrySaplingBlock;
import ru.power_umc.forestxreborn.block.MulberryPressurePlateBlock;
import ru.power_umc.forestxreborn.block.MulberryPlanksBlock;
import ru.power_umc.forestxreborn.block.MulberryParquetBlock;
import ru.power_umc.forestxreborn.block.MulberryLogBlock;
import ru.power_umc.forestxreborn.block.MulberryLeavesWithoutWhiteBlock;
import ru.power_umc.forestxreborn.block.MulberryLeavesWithoutBlackBlock;
import ru.power_umc.forestxreborn.block.MulberryLeavesWithWhiteBlock;
import ru.power_umc.forestxreborn.block.MulberryLeavesWithBlackBlock;
import ru.power_umc.forestxreborn.block.MulberryFenceGateBlock;
import ru.power_umc.forestxreborn.block.MulberryFenceBlock;
import ru.power_umc.forestxreborn.block.MulberryDoorBlock;
import ru.power_umc.forestxreborn.block.MulberryButtonBlock;
import ru.power_umc.forestxreborn.block.MoonshroomBlock;
import ru.power_umc.forestxreborn.block.MarbleBricksWallBlock;
import ru.power_umc.forestxreborn.block.MarbleBricksStairsBlock;
import ru.power_umc.forestxreborn.block.MarbleBricksSlabBlock;
import ru.power_umc.forestxreborn.block.MarbleBricksBlock;
import ru.power_umc.forestxreborn.block.MarbleBlock;
import ru.power_umc.forestxreborn.block.MangroveParquetBlock;
import ru.power_umc.forestxreborn.block.MagentaStairsBlock;
import ru.power_umc.forestxreborn.block.MagentaSlabBlock;
import ru.power_umc.forestxreborn.block.MagentaPlanksBlock;
import ru.power_umc.forestxreborn.block.MagentaFenceGateBlock;
import ru.power_umc.forestxreborn.block.MagentaFenceBlock;
import ru.power_umc.forestxreborn.block.LimeStairsBlock;
import ru.power_umc.forestxreborn.block.LimeSlabBlock;
import ru.power_umc.forestxreborn.block.LimePlanksBlock;
import ru.power_umc.forestxreborn.block.LimeFenceGateBlock;
import ru.power_umc.forestxreborn.block.LimeFenceBlock;
import ru.power_umc.forestxreborn.block.LightGrayStairsBlock;
import ru.power_umc.forestxreborn.block.LightGraySlabBlock;
import ru.power_umc.forestxreborn.block.LightGrayPlanksBlock;
import ru.power_umc.forestxreborn.block.LightGrayFenceGateBlock;
import ru.power_umc.forestxreborn.block.LightGrayFenceBlock;
import ru.power_umc.forestxreborn.block.LightBlueStairsBlock;
import ru.power_umc.forestxreborn.block.LightBlueSlabBlock;
import ru.power_umc.forestxreborn.block.LightBluePlanksBlock;
import ru.power_umc.forestxreborn.block.LightBlueFenceGateBlock;
import ru.power_umc.forestxreborn.block.LightBlueFenceBlock;
import ru.power_umc.forestxreborn.block.LettuceStage3Block;
import ru.power_umc.forestxreborn.block.LettuceStage2Block;
import ru.power_umc.forestxreborn.block.LettuceStage1Block;
import ru.power_umc.forestxreborn.block.LettuceStage0Block;
import ru.power_umc.forestxreborn.block.LavanderBlock;
import ru.power_umc.forestxreborn.block.GreenStairsBlock;
import ru.power_umc.forestxreborn.block.GreenSlabBlock;
import ru.power_umc.forestxreborn.block.GreenPlanksBlock;
import ru.power_umc.forestxreborn.block.GreenFenceGateBlock;
import ru.power_umc.forestxreborn.block.GreenFenceBlock;
import ru.power_umc.forestxreborn.block.GrayStairsBlock;
import ru.power_umc.forestxreborn.block.GraySlabBlock;
import ru.power_umc.forestxreborn.block.GrayPlanksBlock;
import ru.power_umc.forestxreborn.block.GrayFenceGateBlock;
import ru.power_umc.forestxreborn.block.GrayFenceBlock;
import ru.power_umc.forestxreborn.block.GrapeVine1Block;
import ru.power_umc.forestxreborn.block.GrapeVine0Block;
import ru.power_umc.forestxreborn.block.GoldPlatedMarbleBlock;
import ru.power_umc.forestxreborn.block.GingerbreadBricksBlock;
import ru.power_umc.forestxreborn.block.GingerbreadBlockBlock;
import ru.power_umc.forestxreborn.block.FermentationBarrelBlock;
import ru.power_umc.forestxreborn.block.ExposedCopperLadderBlock;
import ru.power_umc.forestxreborn.block.EucalyptusWoodBlock;
import ru.power_umc.forestxreborn.block.EucalyptusTrapdoorBlock;
import ru.power_umc.forestxreborn.block.EucalyptusStairsBlock;
import ru.power_umc.forestxreborn.block.EucalyptusSlabBlock;
import ru.power_umc.forestxreborn.block.EucalyptusSaplingBlock;
import ru.power_umc.forestxreborn.block.EucalyptusPressurePlateBlock;
import ru.power_umc.forestxreborn.block.EucalyptusPlanksBlock;
import ru.power_umc.forestxreborn.block.EucalyptusParquetBlock;
import ru.power_umc.forestxreborn.block.EucalyptusLogBlock;
import ru.power_umc.forestxreborn.block.EucalyptusLeavesBlock;
import ru.power_umc.forestxreborn.block.EucalyptusFenceGateBlock;
import ru.power_umc.forestxreborn.block.EucalyptusFenceBlock;
import ru.power_umc.forestxreborn.block.EucalyptusDoorBlock;
import ru.power_umc.forestxreborn.block.EucalyptusButtonBlock;
import ru.power_umc.forestxreborn.block.DesertRoseBlock;
import ru.power_umc.forestxreborn.block.DenseWebWithSpiderBlock;
import ru.power_umc.forestxreborn.block.DenseWebBlock;
import ru.power_umc.forestxreborn.block.DeepslateSilverOreBlock;
import ru.power_umc.forestxreborn.block.DeepslateSapphireOreBlock;
import ru.power_umc.forestxreborn.block.DarkOakParquetBlock;
import ru.power_umc.forestxreborn.block.CyanStairsBlock;
import ru.power_umc.forestxreborn.block.CyanSlabBlock;
import ru.power_umc.forestxreborn.block.CyanPlanksBlock;
import ru.power_umc.forestxreborn.block.CyanFenceGateBlock;
import ru.power_umc.forestxreborn.block.CyanFenceBlock;
import ru.power_umc.forestxreborn.block.CrushedSandstoneWallBlock;
import ru.power_umc.forestxreborn.block.CrushedSandstoneStairsBlock;
import ru.power_umc.forestxreborn.block.CrushedSandstoneSlabBlock;
import ru.power_umc.forestxreborn.block.CrushedSandstoneBlock;
import ru.power_umc.forestxreborn.block.CrimsonParquetBlock;
import ru.power_umc.forestxreborn.block.CopperLadderBlock;
import ru.power_umc.forestxreborn.block.CobbledSandslateWallBlock;
import ru.power_umc.forestxreborn.block.CobbledSandslateStairsBlock;
import ru.power_umc.forestxreborn.block.CobbledSandslateSlabBlock;
import ru.power_umc.forestxreborn.block.CobbledSandslateBlock;
import ru.power_umc.forestxreborn.block.ChiseledRhyoliteBlock;
import ru.power_umc.forestxreborn.block.CherryParquetBlock;
import ru.power_umc.forestxreborn.block.CattailBlock;
import ru.power_umc.forestxreborn.block.BurningblossomBlock;
import ru.power_umc.forestxreborn.block.BrownStairsBlock;
import ru.power_umc.forestxreborn.block.BrownSlabBlock;
import ru.power_umc.forestxreborn.block.BrownPlanksBlock;
import ru.power_umc.forestxreborn.block.BrownFenceGateBlock;
import ru.power_umc.forestxreborn.block.BrownFenceBlock;
import ru.power_umc.forestxreborn.block.BrownBearCarpetBlock;
import ru.power_umc.forestxreborn.block.BlueberryBush1Block;
import ru.power_umc.forestxreborn.block.BlueberryBush0Block;
import ru.power_umc.forestxreborn.block.BlueStairsBlock;
import ru.power_umc.forestxreborn.block.BlueSlabBlock;
import ru.power_umc.forestxreborn.block.BlueRoseBlock;
import ru.power_umc.forestxreborn.block.BluePlanksBlock;
import ru.power_umc.forestxreborn.block.BlueFenceGateBlock;
import ru.power_umc.forestxreborn.block.BlueFenceBlock;
import ru.power_umc.forestxreborn.block.BlackStairsBlock;
import ru.power_umc.forestxreborn.block.BlackSlabBlock;
import ru.power_umc.forestxreborn.block.BlackPlanksBlock;
import ru.power_umc.forestxreborn.block.BlackMarbleBlock;
import ru.power_umc.forestxreborn.block.BlackFenceGateBlock;
import ru.power_umc.forestxreborn.block.BlackFenceBlock;
import ru.power_umc.forestxreborn.block.BirchParquetBlock;
import ru.power_umc.forestxreborn.block.AshCoverBlock;
import ru.power_umc.forestxreborn.block.AshBlockBlock;
import ru.power_umc.forestxreborn.block.AcaciaParquetBlock;
import ru.power_umc.forestxreborn.ForestMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

public class ForestModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ForestMod.MODID);
	public static final RegistryObject<Block> SNAIL_SHELL = REGISTRY.register("snail_shell", () -> new SnailShellBlock());
	public static final RegistryObject<Block> PEAT = REGISTRY.register("peat", () -> new PeatBlock());
	public static final RegistryObject<Block> CRUSHED_SANDSTONE = REGISTRY.register("crushed_sandstone", () -> new CrushedSandstoneBlock());
	public static final RegistryObject<Block> CRUSHED_SANDSTONE_STAIRS = REGISTRY.register("crushed_sandstone_stairs", () -> new CrushedSandstoneStairsBlock());
	public static final RegistryObject<Block> CRUSHED_SANDSTONE_SLAB = REGISTRY.register("crushed_sandstone_slab", () -> new CrushedSandstoneSlabBlock());
	public static final RegistryObject<Block> CRUSHED_SANDSTONE_WALL = REGISTRY.register("crushed_sandstone_wall", () -> new CrushedSandstoneWallBlock());
	public static final RegistryObject<Block> RED_CRUSHED_SANDSTONE = REGISTRY.register("red_crushed_sandstone", () -> new RedCrushedSandstoneBlock());
	public static final RegistryObject<Block> RED_CRUSHED_SANDSTONE_STAIRS = REGISTRY.register("red_crushed_sandstone_stairs", () -> new RedCrushedSandstoneStairsBlock());
	public static final RegistryObject<Block> RED_CRUSHED_SANDSTONE_SLAB = REGISTRY.register("red_crushed_sandstone_slab", () -> new RedCrushedSandstoneSlabBlock());
	public static final RegistryObject<Block> RED_CRUSHED_SANDSTONE_WALL = REGISTRY.register("red_crushed_sandstone_wall", () -> new RedCrushedSandstoneWallBlock());
	public static final RegistryObject<Block> OAK_PARQUET = REGISTRY.register("oak_parquet", () -> new OakParquetBlock());
	public static final RegistryObject<Block> BIRCH_PARQUET = REGISTRY.register("birch_parquet", () -> new BirchParquetBlock());
	public static final RegistryObject<Block> DARK_OAK_PARQUET = REGISTRY.register("dark_oak_parquet", () -> new DarkOakParquetBlock());
	public static final RegistryObject<Block> SPRUCE_PARQUET = REGISTRY.register("spruce_parquet", () -> new SpruceParquetBlock());
	public static final RegistryObject<Block> ACACIA_PARQUET = REGISTRY.register("acacia_parquet", () -> new AcaciaParquetBlock());
	public static final RegistryObject<Block> TROPICAL_PARQUET = REGISTRY.register("tropical_parquet", () -> new TropicalParquetBlock());
	public static final RegistryObject<Block> CRIMSON_PARQUET = REGISTRY.register("crimson_parquet", () -> new CrimsonParquetBlock());
	public static final RegistryObject<Block> WARPED_PARQUET = REGISTRY.register("warped_parquet", () -> new WarpedParquetBlock());
	public static final RegistryObject<Block> MANGROVE_PARQUET = REGISTRY.register("mangrove_parquet", () -> new MangroveParquetBlock());
	public static final RegistryObject<Block> CHERRY_PARQUET = REGISTRY.register("cherry_parquet", () -> new CherryParquetBlock());
	public static final RegistryObject<Block> MULBERRY_PARQUET = REGISTRY.register("mulberry_parquet", () -> new MulberryParquetBlock());
	public static final RegistryObject<Block> EUCALYPTUS_PARQUET = REGISTRY.register("eucalyptus_parquet", () -> new EucalyptusParquetBlock());
	public static final RegistryObject<Block> BLACK_MARBLE = REGISTRY.register("black_marble", () -> new BlackMarbleBlock());
	public static final RegistryObject<Block> PINKISH_MARBLE = REGISTRY.register("pinkish_marble", () -> new PinkishMarbleBlock());
	public static final RegistryObject<Block> GOLD_PLATED_MARBLE = REGISTRY.register("gold_plated_marble", () -> new GoldPlatedMarbleBlock());
	public static final RegistryObject<Block> MARBLE = REGISTRY.register("marble", () -> new MarbleBlock());
	public static final RegistryObject<Block> MARBLE_BRICKS = REGISTRY.register("marble_bricks", () -> new MarbleBricksBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE = REGISTRY.register("polished_marble", () -> new PolishedMarbleBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE_SLAB = REGISTRY.register("polished_marble_slab", () -> new PolishedMarbleSlabBlock());
	public static final RegistryObject<Block> MARBLE_BRICKS_SLAB = REGISTRY.register("marble_bricks_slab", () -> new MarbleBricksSlabBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE_STAIRS = REGISTRY.register("polished_marble_stairs", () -> new PolishedMarbleStairsBlock());
	public static final RegistryObject<Block> MARBLE_BRICKS_STAIRS = REGISTRY.register("marble_bricks_stairs", () -> new MarbleBricksStairsBlock());
	public static final RegistryObject<Block> POLISHED_MARBLE_WALL = REGISTRY.register("polished_marble_wall", () -> new PolishedMarbleWallBlock());
	public static final RegistryObject<Block> MARBLE_BRICKS_WALL = REGISTRY.register("marble_bricks_wall", () -> new MarbleBricksWallBlock());
	public static final RegistryObject<Block> RHYOLITE = REGISTRY.register("rhyolite", () -> new RhyoliteBlock());
	public static final RegistryObject<Block> POLISHED_RHYOLITE = REGISTRY.register("polished_rhyolite", () -> new PolishedRhyoliteBlock());
	public static final RegistryObject<Block> RHYOLITE_BRICKS = REGISTRY.register("rhyolite_bricks", () -> new RhyoliteBricksBlock());
	public static final RegistryObject<Block> CHISELED_RHYOLITE = REGISTRY.register("chiseled_rhyolite", () -> new ChiseledRhyoliteBlock());
	public static final RegistryObject<Block> RHYOLITE_SLAB = REGISTRY.register("rhyolite_slab", () -> new RhyoliteSlabBlock());
	public static final RegistryObject<Block> POLISHED_RHYOLITE_SLAB = REGISTRY.register("polished_rhyolite_slab", () -> new PolishedRhyoliteSlabBlock());
	public static final RegistryObject<Block> RHYOLITE_BRICKS_SLAB = REGISTRY.register("rhyolite_bricks_slab", () -> new RhyoliteBricksSlabBlock());
	public static final RegistryObject<Block> RHYOLITE_STAIRS = REGISTRY.register("rhyolite_stairs", () -> new RhyoliteStairsBlock());
	public static final RegistryObject<Block> POLISHED_RHYOLITE_STAIRS = REGISTRY.register("polished_rhyolite_stairs", () -> new PolishedRhyoliteStairsBlock());
	public static final RegistryObject<Block> RHYOLITE_BRICKS_STAIRS = REGISTRY.register("rhyolite_bricks_stairs", () -> new RhyoliteBricksStairsBlock());
	public static final RegistryObject<Block> RHYOLITE_WALL = REGISTRY.register("rhyolite_wall", () -> new RhyoliteWallBlock());
	public static final RegistryObject<Block> POLISHED_RHYOLITE_WALL = REGISTRY.register("polished_rhyolite_wall", () -> new PolishedRhyoliteWallBlock());
	public static final RegistryObject<Block> RHYOLITE_BRICKS_WALL = REGISTRY.register("rhyolite_bricks_wall", () -> new RhyoliteBricksWallBlock());
	public static final RegistryObject<Block> ASH_COVER = REGISTRY.register("ash_cover", () -> new AshCoverBlock());
	public static final RegistryObject<Block> ASH_BLOCK = REGISTRY.register("ash_block", () -> new AshBlockBlock());
	public static final RegistryObject<Block> PUMICE = REGISTRY.register("pumice", () -> new PumiceBlock());
	public static final RegistryObject<Block> POLISHED_PUMICE = REGISTRY.register("polished_pumice", () -> new PolishedPumiceBlock());
	public static final RegistryObject<Block> PUMICE_BRICKS = REGISTRY.register("pumice_bricks", () -> new PumiceBricksBlock());
	public static final RegistryObject<Block> TRUNCATED_PUMICE = REGISTRY.register("truncated_pumice", () -> new TruncatedPumiceBlock());
	public static final RegistryObject<Block> TRUNCATED_CARVED_PUMICE = REGISTRY.register("truncated_carved_pumice", () -> new TruncatedCarvedPumiceBlock());
	public static final RegistryObject<Block> PUMICE_SLAB = REGISTRY.register("pumice_slab", () -> new PumiceSlabBlock());
	public static final RegistryObject<Block> POLISHED_PUMICE_SLAB = REGISTRY.register("polished_pumice_slab", () -> new PolishedPumiceSlabBlock());
	public static final RegistryObject<Block> PUMICE_BRICKS_SLAB = REGISTRY.register("pumice_bricks_slab", () -> new PumiceBricksSlabBlock());
	public static final RegistryObject<Block> TRUNCATED_PUMICE_SLAB = REGISTRY.register("truncated_pumice_slab", () -> new TruncatedPumiceSlabBlock());
	public static final RegistryObject<Block> PUMICE_STAIRS = REGISTRY.register("pumice_stairs", () -> new PumiceStairsBlock());
	public static final RegistryObject<Block> POLISHED_PUMICE_STAIRS = REGISTRY.register("polished_pumice_stairs", () -> new PolishedPumiceStairsBlock());
	public static final RegistryObject<Block> PUMICE_BRICKS_STAIRS = REGISTRY.register("pumice_bricks_stairs", () -> new PumiceBricksStairsBlock());
	public static final RegistryObject<Block> TRUNCATED_PUMICE_STAIRS = REGISTRY.register("truncated_pumice_stairs", () -> new TruncatedPumiceStairsBlock());
	public static final RegistryObject<Block> PUMICE_WALL = REGISTRY.register("pumice_wall", () -> new PumiceWallBlock());
	public static final RegistryObject<Block> POLISHED_PUMICE_WALL = REGISTRY.register("polished_pumice_wall", () -> new PolishedPumiceWallBlock());
	public static final RegistryObject<Block> PUMICE_BRICKS_WALL = REGISTRY.register("pumice_bricks_wall", () -> new PumiceBricksWallBlock());
	public static final RegistryObject<Block> TRUNCATED_PUMICE_WALL = REGISTRY.register("truncated_pumice_wall", () -> new TruncatedPumiceWallBlock());
	public static final RegistryObject<Block> SANDSLATE = REGISTRY.register("sandslate", () -> new SandslateBlock());
	public static final RegistryObject<Block> COBBLED_SANDSLATE = REGISTRY.register("cobbled_sandslate", () -> new CobbledSandslateBlock());
	public static final RegistryObject<Block> POLISHED_SANDSLATE = REGISTRY.register("polished_sandslate", () -> new PolishedSandslateBlock());
	public static final RegistryObject<Block> SANDSLATE_BRICKS = REGISTRY.register("sandslate_bricks", () -> new SandslateBricksBlock());
	public static final RegistryObject<Block> SANDSLATE_FACETED_BRICKS = REGISTRY.register("sandslate_faceted_bricks", () -> new SandslateFacetedBricksBlock());
	public static final RegistryObject<Block> COBBLED_SANDSLATE_SLAB = REGISTRY.register("cobbled_sandslate_slab", () -> new CobbledSandslateSlabBlock());
	public static final RegistryObject<Block> POLISHED_SANDSLATE_SLAB = REGISTRY.register("polished_sandslate_slab", () -> new PolishedSandslateSlabBlock());
	public static final RegistryObject<Block> SANDSLATE_BRICKS_SLAB = REGISTRY.register("sandslate_bricks_slab", () -> new SandslateBricksSlabBlock());
	public static final RegistryObject<Block> COBBLED_SANDSLATE_STAIRS = REGISTRY.register("cobbled_sandslate_stairs", () -> new CobbledSandslateStairsBlock());
	public static final RegistryObject<Block> POLISHED_SANDSLATE_STAIRS = REGISTRY.register("polished_sandslate_stairs", () -> new PolishedSandslateStairsBlock());
	public static final RegistryObject<Block> SANDSLATE_BRICKS_STAIRS = REGISTRY.register("sandslate_bricks_stairs", () -> new SandslateBricksStairsBlock());
	public static final RegistryObject<Block> COBBLED_SANDSLATE_WALL = REGISTRY.register("cobbled_sandslate_wall", () -> new CobbledSandslateWallBlock());
	public static final RegistryObject<Block> POLISHED_SANDSLATE_WALL = REGISTRY.register("polished_sandslate_wall", () -> new PolishedSandslateWallBlock());
	public static final RegistryObject<Block> SANDSLATE_BRICKS_WALL = REGISTRY.register("sandslate_bricks_wall", () -> new SandslateBricksWallBlock());
	public static final RegistryObject<Block> RAW_GINGERBREAD_BLOCK = REGISTRY.register("raw_gingerbread_block", () -> new RawGingerbreadBlockBlock());
	public static final RegistryObject<Block> GINGERBREAD_BLOCK = REGISTRY.register("gingerbread_block", () -> new GingerbreadBlockBlock());
	public static final RegistryObject<Block> GINGERBREAD_BRICKS = REGISTRY.register("gingerbread_bricks", () -> new GingerbreadBricksBlock());
	public static final RegistryObject<Block> WHITE_PLANKS = REGISTRY.register("white_planks", () -> new WhitePlanksBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_PLANKS = REGISTRY.register("light_gray_planks", () -> new LightGrayPlanksBlock());
	public static final RegistryObject<Block> GRAY_PLANKS = REGISTRY.register("gray_planks", () -> new GrayPlanksBlock());
	public static final RegistryObject<Block> BLACK_PLANKS = REGISTRY.register("black_planks", () -> new BlackPlanksBlock());
	public static final RegistryObject<Block> BROWN_PLANKS = REGISTRY.register("brown_planks", () -> new BrownPlanksBlock());
	public static final RegistryObject<Block> RED_PLANKS = REGISTRY.register("red_planks", () -> new RedPlanksBlock());
	public static final RegistryObject<Block> ORANGE_PLANKS = REGISTRY.register("orange_planks", () -> new OrangePlanksBlock());
	public static final RegistryObject<Block> YELLOW_PLANKS = REGISTRY.register("yellow_planks", () -> new YellowPlanksBlock());
	public static final RegistryObject<Block> LIME_PLANKS = REGISTRY.register("lime_planks", () -> new LimePlanksBlock());
	public static final RegistryObject<Block> GREEN_PLANKS = REGISTRY.register("green_planks", () -> new GreenPlanksBlock());
	public static final RegistryObject<Block> CYAN_PLANKS = REGISTRY.register("cyan_planks", () -> new CyanPlanksBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_PLANKS = REGISTRY.register("light_blue_planks", () -> new LightBluePlanksBlock());
	public static final RegistryObject<Block> BLUE_PLANKS = REGISTRY.register("blue_planks", () -> new BluePlanksBlock());
	public static final RegistryObject<Block> PURPLE_PLANKS = REGISTRY.register("purple_planks", () -> new PurplePlanksBlock());
	public static final RegistryObject<Block> MAGENTA_PLANKS = REGISTRY.register("magenta_planks", () -> new MagentaPlanksBlock());
	public static final RegistryObject<Block> PINK_PLANKS = REGISTRY.register("pink_planks", () -> new PinkPlanksBlock());
	public static final RegistryObject<Block> WHITE_STAIRS = REGISTRY.register("white_stairs", () -> new WhiteStairsBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_STAIRS = REGISTRY.register("light_gray_stairs", () -> new LightGrayStairsBlock());
	public static final RegistryObject<Block> GRAY_STAIRS = REGISTRY.register("gray_stairs", () -> new GrayStairsBlock());
	public static final RegistryObject<Block> BLACK_STAIRS = REGISTRY.register("black_stairs", () -> new BlackStairsBlock());
	public static final RegistryObject<Block> BROWN_STAIRS = REGISTRY.register("brown_stairs", () -> new BrownStairsBlock());
	public static final RegistryObject<Block> RED_STAIRS = REGISTRY.register("red_stairs", () -> new RedStairsBlock());
	public static final RegistryObject<Block> ORANGE_STAIRS = REGISTRY.register("orange_stairs", () -> new OrangeStairsBlock());
	public static final RegistryObject<Block> YELLOW_STAIRS = REGISTRY.register("yellow_stairs", () -> new YellowStairsBlock());
	public static final RegistryObject<Block> LIME_STAIRS = REGISTRY.register("lime_stairs", () -> new LimeStairsBlock());
	public static final RegistryObject<Block> GREEN_STAIRS = REGISTRY.register("green_stairs", () -> new GreenStairsBlock());
	public static final RegistryObject<Block> CYAN_STAIRS = REGISTRY.register("cyan_stairs", () -> new CyanStairsBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_STAIRS = REGISTRY.register("light_blue_stairs", () -> new LightBlueStairsBlock());
	public static final RegistryObject<Block> BLUE_STAIRS = REGISTRY.register("blue_stairs", () -> new BlueStairsBlock());
	public static final RegistryObject<Block> PURPLE_STAIRS = REGISTRY.register("purple_stairs", () -> new PurpleStairsBlock());
	public static final RegistryObject<Block> MAGENTA_STAIRS = REGISTRY.register("magenta_stairs", () -> new MagentaStairsBlock());
	public static final RegistryObject<Block> PINK_STAIRS = REGISTRY.register("pink_stairs", () -> new PinkStairsBlock());
	public static final RegistryObject<Block> WHITE_SLAB = REGISTRY.register("white_slab", () -> new WhiteSlabBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_SLAB = REGISTRY.register("light_gray_slab", () -> new LightGraySlabBlock());
	public static final RegistryObject<Block> GRAY_SLAB = REGISTRY.register("gray_slab", () -> new GraySlabBlock());
	public static final RegistryObject<Block> BLACK_SLAB = REGISTRY.register("black_slab", () -> new BlackSlabBlock());
	public static final RegistryObject<Block> BROWN_SLAB = REGISTRY.register("brown_slab", () -> new BrownSlabBlock());
	public static final RegistryObject<Block> RED_SLAB = REGISTRY.register("red_slab", () -> new RedSlabBlock());
	public static final RegistryObject<Block> ORANGE_SLAB = REGISTRY.register("orange_slab", () -> new OrangeSlabBlock());
	public static final RegistryObject<Block> YELLOW_SLAB = REGISTRY.register("yellow_slab", () -> new YellowSlabBlock());
	public static final RegistryObject<Block> LIME_SLAB = REGISTRY.register("lime_slab", () -> new LimeSlabBlock());
	public static final RegistryObject<Block> GREEN_SLAB = REGISTRY.register("green_slab", () -> new GreenSlabBlock());
	public static final RegistryObject<Block> CYAN_SLAB = REGISTRY.register("cyan_slab", () -> new CyanSlabBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_SLAB = REGISTRY.register("light_blue_slab", () -> new LightBlueSlabBlock());
	public static final RegistryObject<Block> BLUE_SLAB = REGISTRY.register("blue_slab", () -> new BlueSlabBlock());
	public static final RegistryObject<Block> PURPLE_SLAB = REGISTRY.register("purple_slab", () -> new PurpleSlabBlock());
	public static final RegistryObject<Block> MAGENTA_SLAB = REGISTRY.register("magenta_slab", () -> new MagentaSlabBlock());
	public static final RegistryObject<Block> PINK_SLAB = REGISTRY.register("pink_slab", () -> new PinkSlabBlock());
	public static final RegistryObject<Block> WHITE_FENCE = REGISTRY.register("white_fence", () -> new WhiteFenceBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_FENCE = REGISTRY.register("light_gray_fence", () -> new LightGrayFenceBlock());
	public static final RegistryObject<Block> GRAY_FENCE = REGISTRY.register("gray_fence", () -> new GrayFenceBlock());
	public static final RegistryObject<Block> BLACK_FENCE = REGISTRY.register("black_fence", () -> new BlackFenceBlock());
	public static final RegistryObject<Block> BROWN_FENCE = REGISTRY.register("brown_fence", () -> new BrownFenceBlock());
	public static final RegistryObject<Block> RED_FENCE = REGISTRY.register("red_fence", () -> new RedFenceBlock());
	public static final RegistryObject<Block> ORANGE_FENCE = REGISTRY.register("orange_fence", () -> new OrangeFenceBlock());
	public static final RegistryObject<Block> YELLOW_FENCE = REGISTRY.register("yellow_fence", () -> new YellowFenceBlock());
	public static final RegistryObject<Block> LIME_FENCE = REGISTRY.register("lime_fence", () -> new LimeFenceBlock());
	public static final RegistryObject<Block> GREEN_FENCE = REGISTRY.register("green_fence", () -> new GreenFenceBlock());
	public static final RegistryObject<Block> CYAN_FENCE = REGISTRY.register("cyan_fence", () -> new CyanFenceBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_FENCE = REGISTRY.register("light_blue_fence", () -> new LightBlueFenceBlock());
	public static final RegistryObject<Block> BLUE_FENCE = REGISTRY.register("blue_fence", () -> new BlueFenceBlock());
	public static final RegistryObject<Block> PURPLE_FENCE = REGISTRY.register("purple_fence", () -> new PurpleFenceBlock());
	public static final RegistryObject<Block> MAGENTA_FENCE = REGISTRY.register("magenta_fence", () -> new MagentaFenceBlock());
	public static final RegistryObject<Block> PINK_FENCE = REGISTRY.register("pink_fence", () -> new PinkFenceBlock());
	public static final RegistryObject<Block> WHITE_FENCE_GATE = REGISTRY.register("white_fence_gate", () -> new WhiteFenceGateBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_FENCE_GATE = REGISTRY.register("light_gray_fence_gate", () -> new LightGrayFenceGateBlock());
	public static final RegistryObject<Block> GRAY_FENCE_GATE = REGISTRY.register("gray_fence_gate", () -> new GrayFenceGateBlock());
	public static final RegistryObject<Block> BLACK_FENCE_GATE = REGISTRY.register("black_fence_gate", () -> new BlackFenceGateBlock());
	public static final RegistryObject<Block> BROWN_FENCE_GATE = REGISTRY.register("brown_fence_gate", () -> new BrownFenceGateBlock());
	public static final RegistryObject<Block> RED_FENCE_GATE = REGISTRY.register("red_fence_gate", () -> new RedFenceGateBlock());
	public static final RegistryObject<Block> ORANGE_FENCE_GATE = REGISTRY.register("orange_fence_gate", () -> new OrangeFenceGateBlock());
	public static final RegistryObject<Block> YELLOW_FENCE_GATE = REGISTRY.register("yellow_fence_gate", () -> new YellowFenceGateBlock());
	public static final RegistryObject<Block> LIME_FENCE_GATE = REGISTRY.register("lime_fence_gate", () -> new LimeFenceGateBlock());
	public static final RegistryObject<Block> GREEN_FENCE_GATE = REGISTRY.register("green_fence_gate", () -> new GreenFenceGateBlock());
	public static final RegistryObject<Block> CYAN_FENCE_GATE = REGISTRY.register("cyan_fence_gate", () -> new CyanFenceGateBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_FENCE_GATE = REGISTRY.register("light_blue_fence_gate", () -> new LightBlueFenceGateBlock());
	public static final RegistryObject<Block> BLUE_FENCE_GATE = REGISTRY.register("blue_fence_gate", () -> new BlueFenceGateBlock());
	public static final RegistryObject<Block> PURPLE_FENCE_GATE = REGISTRY.register("purple_fence_gate", () -> new PurpleFenceGateBlock());
	public static final RegistryObject<Block> MAGENTA_FENCE_GATE = REGISTRY.register("magenta_fence_gate", () -> new MagentaFenceGateBlock());
	public static final RegistryObject<Block> PINK_FENCE_GATE = REGISTRY.register("pink_fence_gate", () -> new PinkFenceGateBlock());
	public static final RegistryObject<Block> BROWN_BEAR_CARPET = REGISTRY.register("brown_bear_carpet", () -> new BrownBearCarpetBlock());
	public static final RegistryObject<Block> POLAR_BEAR_CARPET = REGISTRY.register("polar_bear_carpet", () -> new PolarBearCarpetBlock());
	public static final RegistryObject<Block> COPPER_LADDER = REGISTRY.register("copper_ladder", () -> new CopperLadderBlock());
	public static final RegistryObject<Block> EXPOSED_COPPER_LADDER = REGISTRY.register("exposed_copper_ladder", () -> new ExposedCopperLadderBlock());
	public static final RegistryObject<Block> WEATHERED_COPPER_LADDER = REGISTRY.register("weathered_copper_ladder", () -> new WeatheredCopperLadderBlock());
	public static final RegistryObject<Block> OXIDIZED_COPPER_LADDER = REGISTRY.register("oxidized_copper_ladder", () -> new OxidizedCopperLadderBlock());
	public static final RegistryObject<Block> WAXED_COPPER_LADDER = REGISTRY.register("waxed_copper_ladder", () -> new WaxedCopperLadderBlock());
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_LADDER = REGISTRY.register("waxed_exposed_copper_ladder", () -> new WaxedExposedCopperLadderBlock());
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_LADDER = REGISTRY.register("waxed_weathered_copper_ladder", () -> new WaxedWeatheredCopperLadderBlock());
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_LADDER = REGISTRY.register("waxed_oxidized_copper_ladder", () -> new WaxedOxidizedCopperLadderBlock());
	public static final RegistryObject<Block> WILDFLOWER = REGISTRY.register("wildflower", () -> new WildflowerBlock());
	public static final RegistryObject<Block> BURNING_BLOSSOM = REGISTRY.register("burning_blossom", () -> new BurningblossomBlock());
	public static final RegistryObject<Block> LAVANDER = REGISTRY.register("lavander", () -> new LavanderBlock());
	public static final RegistryObject<Block> DESERT_ROSE = REGISTRY.register("desert_rose", () -> new DesertRoseBlock());
	public static final RegistryObject<Block> BLUE_ROSE = REGISTRY.register("blue_rose", () -> new BlueRoseBlock());
	public static final RegistryObject<Block> SUNSHROOM = REGISTRY.register("sunshroom", () -> new SunshroomBlock());
	public static final RegistryObject<Block> MOONSHROOM = REGISTRY.register("moonshroom", () -> new MoonshroomBlock());
	public static final RegistryObject<Block> GRAPE_VINE_0 = REGISTRY.register("grape_vine_0", () -> new GrapeVine0Block());
	public static final RegistryObject<Block> WHITE_ROSE_BUSH = REGISTRY.register("white_rose_bush", () -> new WhiteRoseBushBlock());
	public static final RegistryObject<Block> PINK_ROSE_BUSH = REGISTRY.register("pink_rose_bush", () -> new PinkRoseBushBlock());
	public static final RegistryObject<Block> CATTAIL = REGISTRY.register("cattail", () -> new CattailBlock());
	public static final RegistryObject<Block> SILVER_ORE = REGISTRY.register("silver_ore", () -> new SilverOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SILVER_ORE = REGISTRY.register("deepslate_silver_ore", () -> new DeepslateSilverOreBlock());
	public static final RegistryObject<Block> RAW_SILVER_BLOCK = REGISTRY.register("raw_silver_block", () -> new RawSilverBlockBlock());
	public static final RegistryObject<Block> SILVER_BLOCK = REGISTRY.register("silver_block", () -> new SilverBlockBlock());
	public static final RegistryObject<Block> FERMENTATION_BARREL = REGISTRY.register("fermentation_barrel", () -> new FermentationBarrelBlock());
	public static final RegistryObject<Block> MULBERRY_SAPLING = REGISTRY.register("mulberry_sapling", () -> new MulberrySaplingBlock());
	public static final RegistryObject<Block> MULBERRY_LEAVES_WITHOUT_WHITE = REGISTRY.register("mulberry_leaves_without_white", () -> new MulberryLeavesWithoutWhiteBlock());
	public static final RegistryObject<Block> MULBERRY_LEAVES_WITHOUT_BLACK = REGISTRY.register("mulberry_leaves_without_black", () -> new MulberryLeavesWithoutBlackBlock());
	public static final RegistryObject<Block> MULBERRY_LEAVES_WITH_WHITE = REGISTRY.register("mulberry_leaves_with_white", () -> new MulberryLeavesWithWhiteBlock());
	public static final RegistryObject<Block> MULBERRY_LEAVES_WITH_BLACK = REGISTRY.register("mulberry_leaves_with_black", () -> new MulberryLeavesWithBlackBlock());
	public static final RegistryObject<Block> MULBERRY_LOG = REGISTRY.register("mulberry_log", () -> new MulberryLogBlock());
	public static final RegistryObject<Block> MULBERRY_WOOD = REGISTRY.register("mulberry_wood", () -> new MulberryWoodBlock());
	public static final RegistryObject<Block> STRIPPED_MULBERRY_LOG = REGISTRY.register("stripped_mulberry_log", () -> new StrippedMulberryLogBlock());
	public static final RegistryObject<Block> STRIPPED_MULBERRY_WOOD = REGISTRY.register("stripped_mulberry_wood", () -> new StrippedMulberryWoodBlock());
	public static final RegistryObject<Block> MULBERRY_PLANKS = REGISTRY.register("mulberry_planks", () -> new MulberryPlanksBlock());
	public static final RegistryObject<Block> MULBERRY_STAIRS = REGISTRY.register("mulberry_stairs", () -> new MulberryStairsBlock());
	public static final RegistryObject<Block> MULBERRY_SLAB = REGISTRY.register("mulberry_slab", () -> new MulberrySlabBlock());
	public static final RegistryObject<Block> MULBERRY_FENCE = REGISTRY.register("mulberry_fence", () -> new MulberryFenceBlock());
	public static final RegistryObject<Block> MULBERRY_FENCE_GATE = REGISTRY.register("mulberry_fence_gate", () -> new MulberryFenceGateBlock());
	public static final RegistryObject<Block> MULBERRY_DOOR = REGISTRY.register("mulberry_door", () -> new MulberryDoorBlock());
	public static final RegistryObject<Block> MULBERRY_TRAPDOOR = REGISTRY.register("mulberry_trapdoor", () -> new MulberryTrapdoorBlock());
	public static final RegistryObject<Block> MULBERRY_PRESSURE_PLATE = REGISTRY.register("mulberry_pressure_plate", () -> new MulberryPressurePlateBlock());
	public static final RegistryObject<Block> MULBERRY_BUTTON = REGISTRY.register("mulberry_button", () -> new MulberryButtonBlock());
	public static final RegistryObject<Block> EUCALYPTUS_SAPLING = REGISTRY.register("eucalyptus_sapling", () -> new EucalyptusSaplingBlock());
	public static final RegistryObject<Block> EUCALYPTUS_LEAVES = REGISTRY.register("eucalyptus_leaves", () -> new EucalyptusLeavesBlock());
	public static final RegistryObject<Block> EUCALYPTUS_LOG = REGISTRY.register("eucalyptus_log", () -> new EucalyptusLogBlock());
	public static final RegistryObject<Block> EUCALYPTUS_WOOD = REGISTRY.register("eucalyptus_wood", () -> new EucalyptusWoodBlock());
	public static final RegistryObject<Block> STRIPPED_EUCALYPTUS_LOG = REGISTRY.register("stripped_eucalyptus_log", () -> new StrippedEucalyptusLogBlock());
	public static final RegistryObject<Block> STRIPPED_EUCALYPTUS_WOOD = REGISTRY.register("stripped_eucalyptus_wood", () -> new StrippedEucalyptusWoodBlock());
	public static final RegistryObject<Block> EUCALYPTUS_PLANKS = REGISTRY.register("eucalyptus_planks", () -> new EucalyptusPlanksBlock());
	public static final RegistryObject<Block> EUCALYPTUS_STAIRS = REGISTRY.register("eucalyptus_stairs", () -> new EucalyptusStairsBlock());
	public static final RegistryObject<Block> EUCALYPTUS_SLAB = REGISTRY.register("eucalyptus_slab", () -> new EucalyptusSlabBlock());
	public static final RegistryObject<Block> EUCALYPTUS_FENCE = REGISTRY.register("eucalyptus_fence", () -> new EucalyptusFenceBlock());
	public static final RegistryObject<Block> EUCALYPTUS_FENCE_GATE = REGISTRY.register("eucalyptus_fence_gate", () -> new EucalyptusFenceGateBlock());
	public static final RegistryObject<Block> EUCALYPTUS_DOOR = REGISTRY.register("eucalyptus_door", () -> new EucalyptusDoorBlock());
	public static final RegistryObject<Block> EUCALYPTUS_TRAPDOOR = REGISTRY.register("eucalyptus_trapdoor", () -> new EucalyptusTrapdoorBlock());
	public static final RegistryObject<Block> EUCALYPTUS_PRESSURE_PLATE = REGISTRY.register("eucalyptus_pressure_plate", () -> new EucalyptusPressurePlateBlock());
	public static final RegistryObject<Block> EUCALYPTUS_BUTTON = REGISTRY.register("eucalyptus_button", () -> new EucalyptusButtonBlock());
	public static final RegistryObject<Block> SAPPHIRE_ORE = REGISTRY.register("sapphire_ore", () -> new SapphireOreBlock());
	public static final RegistryObject<Block> SAPPHIRE_BLOCK = REGISTRY.register("sapphire_block", () -> new SapphireBlockBlock());
	public static final RegistryObject<Block> DEEPSLATE_SAPPHIRE_ORE = REGISTRY.register("deepslate_sapphire_ore", () -> new DeepslateSapphireOreBlock());
	public static final RegistryObject<Block> DENSE_WEB = REGISTRY.register("dense_web", () -> new DenseWebBlock());
	public static final RegistryObject<Block> DENSE_WEB_WITH_SPIDER = REGISTRY.register("dense_web_with_spider", () -> new DenseWebWithSpiderBlock());
	public static final RegistryObject<Block> BLUEBERRY_BUSH_0 = REGISTRY.register("blueberry_bush_0", () -> new BlueberryBush0Block());
	public static final RegistryObject<Block> BLUEBERRY_BUSH_1 = REGISTRY.register("blueberry_bush_1", () -> new BlueberryBush1Block());
	public static final RegistryObject<Block> LETTUCE_STAGE_0 = REGISTRY.register("lettuce_stage_0", () -> new LettuceStage0Block());
	public static final RegistryObject<Block> LETTUCE_STAGE_1 = REGISTRY.register("lettuce_stage_1", () -> new LettuceStage1Block());
	public static final RegistryObject<Block> LETTUCE_STAGE_2 = REGISTRY.register("lettuce_stage_2", () -> new LettuceStage2Block());
	public static final RegistryObject<Block> LETTUCE_STAGE_3 = REGISTRY.register("lettuce_stage_3", () -> new LettuceStage3Block());
	public static final RegistryObject<Block> GRAPE_VINE_1 = REGISTRY.register("grape_vine_1", () -> new GrapeVine1Block());
	public static final RegistryObject<Block> RASPBERRY_BUSH_0 = REGISTRY.register("raspberry_bush_0", () -> new RaspberryBush0Block());
	public static final RegistryObject<Block> RASPBERRY_BUSH_1 = REGISTRY.register("raspberry_bush_1", () -> new RaspberryBush1Block());
	public static final RegistryObject<Block> RASPBERRY_BUSH_2 = REGISTRY.register("raspberry_bush_2", () -> new RaspberryBush2Block());
	public static final RegistryObject<Block> RASPBERRY_BUSH_3 = REGISTRY.register("raspberry_bush_3", () -> new RaspberryBush3Block());
	public static final RegistryObject<Block> RYE_STAGE_0 = REGISTRY.register("rye_stage_0", () -> new RyeStage0Block());
	public static final RegistryObject<Block> RYE_STAGE_1 = REGISTRY.register("rye_stage_1", () -> new RyeStage1Block());
	public static final RegistryObject<Block> RYE_STAGE_2 = REGISTRY.register("rye_stage_2", () -> new RyeStage2Block());
	public static final RegistryObject<Block> RYE_STAGE_3 = REGISTRY.register("rye_stage_3", () -> new RyeStage3Block());
	public static final RegistryObject<Block> RYE_STAGE_4 = REGISTRY.register("rye_stage_4", () -> new RyeStage4Block());
	public static final RegistryObject<Block> RYE_STAGE_5 = REGISTRY.register("rye_stage_5", () -> new RyeStage5Block());
	public static final RegistryObject<Block> RYE_STAGE_6 = REGISTRY.register("rye_stage_6", () -> new RyeStage6Block());
	public static final RegistryObject<Block> RYE_STAGE_7 = REGISTRY.register("rye_stage_7", () -> new RyeStage7Block());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			EucalyptusLeavesBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			EucalyptusLeavesBlock.itemColorLoad(event);
		}
	}
}
